import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import DropZoneComponent from "@/components/DropZone";
import { Main } from "next/document";
import { useState } from "react";
import styled from "@emotion/styled";
import ButtonProcess from "@/components/ButtonProcess";
import { CheckFileHelper } from "@/helper/checkFileHelper";
import { ProcessingFileHelper } from "@/helper/processingFileHelper";
import OutputProcess from "@/components/OutputProcess";
import ButtonDownload from "@/components/ButtonDownload";

const MainContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: calc(100vh - 4rem);
`;

const MainContent = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  gap: 1rem;
  padding-top: 2rem;
  padding-bottom: 2rem;
`;

const Index: NextPage = () => {
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [fileName, setFileName] = useState<string>("");
  const [outputFile, setOutputFile] = useState<Object | null>(null);

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    const { errorMessage, isValid } = CheckFileHelper(file);

    if (!isValid) {
      alert(errorMessage);
      event.target.value = ""; // reset the input field
      return;
    }

    if (outputFile) {
      setOutputFile(null);
    }
    setFileName(file.name);
    setSelectedFile(file);
  };

  const handleButtonProcess = async () => {
    setIsProcessing(true);
    await ProcessingFileHelper(selectedFile)
      .then((res) => {
        setIsProcessing(false);

        if (!res) {
          alert("No file to process. Please upload a file first.");
          return;
        }

        setOutputFile(res);
      })
      .catch((err) => {
        setIsProcessing(false);

        alert("Error processing file: " + err);
        return null;
      });
  };

  return (
    <>
      <Head>
        <title>Media-Kit</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      {/* <LandingPageTemplate /> */}

      <MainContainer>
        <MainContent>
          <DropZoneComponent
            selectedFile={selectedFile}
            fileName={fileName}
            handleFileUpload={handleFileUpload}
          />

          <ButtonProcess
            onClick={() => handleButtonProcess()}
            isProcessing={isProcessing}
          />

          {isProcessing && <p>Processing...</p>}
          {outputFile && (
            <>
              <OutputProcess
                outputFile={outputFile}
                selectedFileSize={selectedFile?.size || 0}
              />
              <ButtonDownload outputFile={outputFile} />
            </>
          )}
        </MainContent>
      </MainContainer>
    </>
  );
};

export default Index;
